#!/bin/bash
echo " | ================================================================================ | "
echo " | exVim installed successfully!                                                    | "
echo " |                                                                                  | "
echo " | ================================================================================ | "
echo " | Read the_silver_searcher info to install tools.                                  | "
echo " |                                                                                  | "
echo " | for ex. centos :                                                                 | "
echo " | wget -c https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm   | "
echo " | sudo rpm -ivh epel-release-latest-7.noarch.rpm                                   | "
echo " | sudo https://github.com/ggreer/the_silver_searcher                               | "
echo " | for ex. Debian :                                                                 | "
echo " | apt-get install silversearcher-ag                                                | "
echo " | ================================================================================ | "
echo " | yum install python-pip                                                           | "
echo " | pip install argparse                                                             | "
echo " | ================================================================================ | "

echo "You can run 'sh unix/gvim.sh' to preview exVim."
echo "You can also run 'sh unix/replace-my-vim.sh' to replace exVim with your Vim."
